In [1]:
from IPython.display import display
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
import konlpy
import re
from wordcloud import WordCloud
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['axes.unicode_minus'] = False

import platform
path = 'c:/Windows/Fonts/malgun.ttf'
from matplotlib import font_manager, rc
if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system... sorry~~~~~')

D:\python2020\lib\site-packages\sklearn\externals\six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
D:\python2020\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)

In [2]:
data1 = pd.read_csv('data.csv',encoding='utf8', sep=',',names=['date','headline','content','num'])

In [6]:
data['datetime'] = data['date'].apply(lambda x: pd.to_datetime(str(x), format='%Y-%m-%d'))

In [7]:
data3 = pd.read_csv("kospi.csv",encoding='utf8', sep=',')

In [8]:
data3['datetime'] = data3['date'].apply(lambda x: pd.to_datetime(str(x), format='%Y-%m-%d'))

In [9]:
data.set_index(data['datetime'], inplace=True)
data3.set_index(data3['datetime'], inplace=True)

In [10]:
data4 = data3['up/down']

In [12]:
data = data.drop('datetime', 1)

In [22]:
data_base=pd.merge(data,data4, on = 'datetime')

In [23]:
data_base

,date,headline,content,num,up/down
datetime,,,,,
2019-04-19,2019-04-19,"NH투자證 `선택과 집중` 통했다…펀드설정액, 증권사 1위에 올라",지난해 말 조직개편을 통해 펀드 판매에 승부수를 띄운 NH투자증권이 올해 들어 금융...,737168,none
2019-04-19,2019-04-19,"FSN, 손자회사 옐로스토리 경영권 포함 지분 전량 매각",종합 디지털 광고 전문기업 퓨쳐스트림네트웍스(이하 FSN)가 손자회사 옐로스토리 매...,737168,none
2019-04-19,2019-04-19,"[Hot-Line] ""DGB금융지주, 증권사 인수효과 가시화…양호한 실적""",IBK투자증권은 19일 DGB금융지주에 대해 하이투자증권 인수효과가 나타나면서 양호...,737168,none
2019-04-18,2019-04-18,"와그트래블, 135억원 자금 확보…글로벌 공략 나선다",[머니투데이 창조기획팀 이동오 기자] [글로벌 여행 액티비티 예약 플랫폼 와그(WA...,737167,0
2019-04-18,2019-04-18,"기업은행, 인도 IIT 경영전문대학과 인재양성 업무협약",IBK기업은행은 인도 뉴델리 소재 IIT(Indian Institute of Tec...,737167,0
...,...,...,...,...,...
2010-05-06,2010-05-06,"인사이드 스포츠 / 여자배구, 6구단이냐 4구단이냐","제6구단이 탄생할까, 아니면 4개 팀으로 축소될까.\n배구계가 뒤숭숭하다. 2009...",733898,0
2010-04-26,2010-04-26,새상품,한국투자증권의 ‘한국투자한국의힘증권1’ 펀드는 세계 경쟁력을 갖춘 한국의 대표 기업...,733888,1
2010-04-23,2010-04-23,IT 봄바람은 계속된다,세계경제의 빠른 회복세 속에 정보통신(IT) 산업이 호황을 기록하면서 국내 기업들 ...,733885,0
2010-04-22,2010-04-22,IT 봄바람은 계속된다,세계경제의 빠른 회복세 속에 정보통신(IT) 산업이 호황을 기록하면서 국내 기업들 ...,733884,0
2010-04-19,2010-04-19,“자전거로 출퇴근하면 금리 더 드려요”,“승용차 요일제에 참여하면 이자를 더 드려요.” \n환경친화적인 기업이나 개인 고객...,733881,0

In [24]:
#data_base1 = data_base.drop(['num','headline','date'], axis=1)

In [25]:
data_base1

                                                      content up/down
datetime
2019-04-19  지난해 말 조직개편을 통해 펀드 판매에 승부수를 띄운 NH투자증권이 올해 들어 금융...    none
2019-04-19  종합 디지털 광고 전문기업 퓨쳐스트림네트웍스(이하 FSN)가 손자회사 옐로스토리 매...    none
2019-04-19  IBK투자증권은 19일 DGB금융지주에 대해 하이투자증권 인수효과가 나타나면서 양호...    none
2019-04-18  [머니투데이 창조기획팀 이동오 기자] [글로벌 여행 액티비티 예약 플랫폼 와그(WA...       0
2019-04-18  IBK기업은행은 인도 뉴델리 소재 IIT(Indian Institute of Tec...       0
...                                                       ...     ...
2010-05-06  제6구단이 탄생할까, 아니면 4개 팀으로 축소될까.\n배구계가 뒤숭숭하다. 2009...       0
2010-04-26  한국투자증권의 ‘한국투자한국의힘증권1’ 펀드는 세계 경쟁력을 갖춘 한국의 대표 기업...       1
2010-04-23  세계경제의 빠른 회복세 속에 정보통신(IT) 산업이 호황을 기록하면서 국내 기업들 ...       0
2010-04-22  세계경제의 빠른 회복세 속에 정보통신(IT) 산업이 호황을 기록하면서 국내 기업들 ...       0
2010-04-19  “승용차 요일제에 참여하면 이자를 더 드려요.” \n환경친화적인 기업이나 개인 고객...       0

[13644 rows x 2 columns]

In [26]:
pd.value_counts(data_base1['up/down'].values, sort=False)

0       5920
none    1644
1       6080
dtype: int64

In [28]:
#none값제거
idx_1 = data_base1[data_base['up/down'] == 'none'].index
data_base2 = data_base1.drop(idx_1)
data_base2

                                                      content up/down
datetime
2019-04-18  [머니투데이 창조기획팀 이동오 기자] [글로벌 여행 액티비티 예약 플랫폼 와그(WA...       0
2019-04-18  IBK기업은행은 인도 뉴델리 소재 IIT(Indian Institute of Tec...       0
2019-04-18  [머니투데이 박광범 기자] 최성재 IBK기업으행 글로벌사업부 본부장(왼쪽)과 산지브...       0
2019-04-18  [머니투데이 양태연 머니투데이방송 PD] \n\n\n\n<시장을 이겨라>\n\n이슈...       0
2019-04-18  안정적인 채권 이자수익과 더불어 페어트레이딩 전략으로 초과수익을 추구하는 미래에셋스...       0
...                                                       ...     ...
2010-05-06  제6구단이 탄생할까, 아니면 4개 팀으로 축소될까.\n배구계가 뒤숭숭하다. 2009...       0
2010-04-26  한국투자증권의 ‘한국투자한국의힘증권1’ 펀드는 세계 경쟁력을 갖춘 한국의 대표 기업...       1
2010-04-23  세계경제의 빠른 회복세 속에 정보통신(IT) 산업이 호황을 기록하면서 국내 기업들 ...       0
2010-04-22  세계경제의 빠른 회복세 속에 정보통신(IT) 산업이 호황을 기록하면서 국내 기업들 ...       0
2010-04-19  “승용차 요일제에 참여하면 이자를 더 드려요.” \n환경친화적인 기업이나 개인 고객...       0

[12000 rows x 2 columns]

In [32]:
data_base3 = data_base2.drop_duplicates(['content'], keep='last')

In [33]:
data_base3

                                                      content up/down
datetime
2019-04-18  [머니투데이 창조기획팀 이동오 기자] [글로벌 여행 액티비티 예약 플랫폼 와그(WA...       0
2019-04-18  IBK기업은행은 인도 뉴델리 소재 IIT(Indian Institute of Tec...       0
2019-04-18  [머니투데이 박광범 기자] 최성재 IBK기업으행 글로벌사업부 본부장(왼쪽)과 산지브...       0
2019-04-18  [머니투데이 양태연 머니투데이방송 PD] \n\n\n\n<시장을 이겨라>\n\n이슈...       0
2019-04-18  안정적인 채권 이자수익과 더불어 페어트레이딩 전략으로 초과수익을 추구하는 미래에셋스...       0
...                                                       ...     ...
2010-05-06  제6구단이 탄생할까, 아니면 4개 팀으로 축소될까.\n배구계가 뒤숭숭하다. 2009...       0
2010-04-26  한국투자증권의 ‘한국투자한국의힘증권1’ 펀드는 세계 경쟁력을 갖춘 한국의 대표 기업...       1
2010-04-23  세계경제의 빠른 회복세 속에 정보통신(IT) 산업이 호황을 기록하면서 국내 기업들 ...       0
2010-04-22  세계경제의 빠른 회복세 속에 정보통신(IT) 산업이 호황을 기록하면서 국내 기업들 ...       0
2010-04-19  “승용차 요일제에 참여하면 이자를 더 드려요.” \n환경친화적인 기업이나 개인 고객...       0

[11821 rows x 2 columns]

In [34]:
data_base3.to_csv("ibk1차데이터1.csv")